config/routes.rb
HorasExtras::Application.routes.draw do


  get "users/sign_out"

  match 'horas-extras' => "overtimes#index"
  match 'registrar-hora-extra' => "overtimes#new"
  match 'aprovando-a-hora-extra/:description' => "overtimes#approve"
  match 'nao-aprovo/:description' => "overtimes#no_approved"
  match 'manager/:project_id' => "overtimes#manager"
  match 'manager' => "overtimes#manager"
  match 'desconto' => "discount#discount"
  match 'rh/:id' => "overtimes#rh"
  match 'rh' => "overtimes#rh"
 

  devise_for :admins

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'


  get "pages/home"
  get "pages/ovos"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :overtimes










  root :to => 'pages#home'


end

app/models/overtime.rb
class Overtime < ActiveRecord::Base
  attr_accessible :description,  :start_overtime, :end_overtime, :user_id, :project_id, :status
  validates_presence_of :description,  :start_overtime, :end_overtime, :user_id, :project_id 

  belongs_to :user, :inverse_of => :overtimes
  belongs_to :project

  def self.rh
    ["luiz.alves@planb.com.br", "jacqueline.pereira@planb.com.br", "viviane.souza@planb.com.br","nayara.oliveira@planb.com.br"]
  end 

  def self.SumOvertimes(current_user)
   	overtimesApproveds = current_user.overtimes.where("status = 'approved'")
    overtime = 0
  	overtimesApproveds.each do | overtimesApproved |
  		overtime += (overtimesApproved.end_overtime - overtimesApproved.start_overtime).to_i
  	end
    overtime
  end 
   
  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_user
      all.each do |overtime|
        csv << overtime.attributes.values_at(*column_user)
      end
    end
  end
end 



#def searchUser
  #  @overtime = Overtime.find(:all, :conditions => ["overtime_user = ? and start_overtime >= 2013-06-10 and end_overtime <=2013-07-30", params[:id]])
   #end

app/controllers/overtimes_controller.rb
class OvertimesController < ApplicationController

  # GET /overtimes
  # GET /overtimes.json
  def index
    @overtimes = current_user.overtimes.all
    @discount = current_user.discount.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @overtimes }
    end
  end


  def new
  	@overtime = Overtime.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @overtime }
    end
  end


  # GET /overtime/1
  # GET /overtime/1.json
  def show
    @overtime = Overtime.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @overtime }
    end
  end
  # POST /overtimes
  # POST /overtimes.json
  def create
    @overtime = Overtime.new(params[:overtime])
    @overtime.user = current_user
    
    #flash[:notice] = "Parabens sua hora extra foi criada"
    

    respond_to do |format|
      if @overtime.save
        begin
          Notification.registration_confirm(@overtime).deliver
        rescue
          
        end
        
        format.html { redirect_to "/registrar-hora-extra", notice: 'SUA HORA EXTRA FOI COMPUTADA, AGUARDE O GESTOR' }
        format.json { render json: @overtime, status: :created, location: @overtime }
      else
        format.html { render action: "new" }
        format.json { render json: @overtime.errors, status: :unprocessable_entity }
      end
    end
  end


  def approve
    #TODO:TROCAR ID POR HASH OU QUALQUER COISA CRIPTOGRAFADA OU TOKEN 
    #status gerar um campo com um default sempre pendente 
    overtime = Overtime.find(params[:id])
    overtime.status = 'approved'

    if overtime.save
      Notification.send_for_rh(overtime).deliver #notifica o RH
      Notification.your_overtime_approved(overtime).deliver #notifica o cara que registrou

      
      respond_to do |format|
        format.html 
        format.json { render json: @overtime }
      end
    else
      format.html { render action: "index" }
      format.json { render json: overtime.errors, status: :unprocessable_entity }
    end
  end

  def no_approved
    #logger.debug "TESTEEE" printar no console
    overtime = Overtime.find(params[:id])

    if overtime.save
      Notification.no_approved(overtime).deliver 

      respond_to do |format|
        format.html 
        format.json { render json: @overtime }
      end
    else
      format.html 
      format.json { render json: overtime.errors, status: :unprocessable_entity }
    end
  end
  def manager
    if params[:project_id].nil?
      @overtime = Overtime.all
      @total_times = (Overtime.SumOvertimes(current_user)/ 3600).to_i
    else
      @overtime = Overtime.where(:project_id => params[:project_id])
      @total_times = (Project.find(params[:project_id]).SumOvertimes/ 3600).to_i
    end

    @projects = current_user.projects

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @overtimes }
    end
  end
  def rh
    @users = User.all

    if params[:id]
      @overtimes = User.find(params[:id]).overtimes.all
    else
      @overtimes = current_user.overtimes.all
    end
   
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @overtimes }
      format.csv { render text: @overtimes}
      format.xls { send_data @overtimes.to_csv(col_sep: "\t") }
    end
  end
end

app/helpers/overtimes_helper.rb
module OvertimesHelper
end

app/views/overtimes/approve.html.erb
Confirmada!

app/views/overtimes/index.html.erb
<%= render "shared/menu" %>

<section class="infoTab">
    <nav id="navInfoTab">
        <a data-aba="InfoHoraExtra" class="abaExtra selected" href="javascript:void(0);">Hora Extra</a>
        <a data-aba="InfoDesconto" class="abaExtra abaRight" href="javascript:void(0);">Desconto</a>
    </nav>

<div class="InfoHoraExtra boxTextos">     
      <div class=""><strong>Total de descontos</strong>: 
      <%
       if humanize((Discount.diff(current_user)).to_i).to_i > 0.to_i 
       %>
        <%= humanize((Discount.diff(current_user)).to_i) %>          
      <% else %>
       <%= "Nenhum Desconto" %> 
      <% end%> 
    </div>
    <div class="pull-right"><strong>Pesquisar</strong> <input id="filter" type="text" /></div>
    <div class="pull-left"><strong>Horas Aprovadas:</strong> <%= humanize((Overtime.SumOvertimes(current_user)).to_i) %>
      <div style="padding-bottom: 10px;"><strong>Saldo</strong>: <% if Overtime.SumOvertimes(current_user).to_i >  Discount.diff(current_user).to_i %>
        
            <span style="color: green"><%= humanize((Overtime.SumOvertimes(current_user).to_i - Discount.diff(current_user).to_i)) %></span>

        <% else %>
            
            
            <span style="color: red"><%= humanize((Discount.diff(current_user).to_i - Overtime.SumOvertimes(current_user).to_i)) %></span>

        <% end %> </div>  
    </div>
    <div style="clear: both;"></div>


    
    <div style="clear: both;"></div>
    <table data-filter="#filter" class="footable">
      <thead>
        <tr>
          <th data-class="expand" data-sort-initial="true">
            Motivo
          </th>
          <th>
            Inicio
          </th>
          <th data-hide="phone,tablet">
            Fim
          </th>
          <th data-hide="phone,tablet" data-type="numeric"> 
            Horas trabalhadas
          </th>
          <th data-hide="phone">
            Projeto
          </th>
          
          <th data-hide="phone">
            Status
          </th>
        </tr>
      </thead>
      <tbody>
        <% @overtimes.each do |overtime| %>
          <tr>
            <td><%= overtime.description %></td>
            <td><%= overtime.start_overtime.strftime('%d/%m/%Y %H:%M') %></td>
            <td><%= overtime.end_overtime.strftime('%d/%m/%Y %H:%M') %></td>
            <td data-value="78025368997"><%= (Time.mktime(0)+(overtime.end_overtime - overtime.start_overtime).to_i).strftime("%H:%M") %></td>
            <td data-value="suspended"><%= overtime.project.name %></td>
            <td data-value="suspended">
              <% if overtime.status == "pedding" 
                  concat image_tag("suspended.png")           
               else overtime.status == "approved"
                  concat image_tag("active.png") 
              end
              %>
          </tr>
      <% end %> 
      </tbody>
    </table>      
    </div>

    <div class="InfoDesconto boxTextos">
      <table data-filter="#filter" class="footable">
      <thead>
        <tr>
          <th data-class="expand" data-sort-initial="true">          
            Descrição
          </th>
          <th>
            Dia da Folga
          </th>
          <th data-hide="phone,tablet">
            Tempo
          </th>        
      </thead>
     <tbody>
        <% @discount.each do |discount|%>
          <tr>
            <td><%= discount.description %></td>
            <td><%= discount.day_off.strftime('%d/%m/%Y') %></td>
            <td><%= discount.time_off.strftime('%H:%M') %></td>
          </tr>
        <% end %> 
     </tbody>
    </table>    
    </div>
    <div class="clear-fix"></div>        
</section> 





        
    


     

app/views/overtimes/manager.html.erb
<h1>Registro do Gestor</h1>

<%= render "shared/menu" %>

    <div class="pull-right"><strong>Total de Horas:</strong>  <%= @total_times %> </div>
    <div class="pull-left" > <%=select("project", "project_id", @projects.collect {|project| [ project.name, project.id ] }, { :prompt => 'Selecione um projeto' }) %></div>
    <table data-filter="#filter" class="footable">
      <thead>
        <tr>
          <th data-class="expand" data-sort-initial="true">
            Projeto
          </th>
          <th>
            Usuario
          </th>
          <th data-hide="phone,tablet">
            Horario Inicial
          </th>
          <th data-hide="phone,tablet" data-type="numeric"> 
            Horario Final
          </th>
          <th data-hide="phone">
            Motivo
          </th>
          
          <th data-hide="phone">
            Status
          </th>
        </tr>
      </thead>
      <tbody>
        <% @overtime.each do |overtime| %>
          <tr>
            <td><%= overtime.project.name %></td>
            <td><%= overtime.user.name %></td>
            <td><%= overtime.start_overtime.strftime('%d/%m/%Y %H:%M') %></td>
            <td><%= overtime.end_overtime.strftime('%d/%m/%Y %H:%M') %></td>
            <td data-value="suspended"><%= overtime.description %></td>
            <td data-value="suspended">
              <% if overtime.status == "pedding" 
                  concat image_tag("suspended.png")           
               else overtime.status == "approved"
                  concat image_tag("active.png") 
              end
              %>              
          </tr>
      <% end %> 
      </tbody>
    </table>

    



     

app/views/overtimes/new.html.erb
<script type="text/javascript">
	$(function() {
		$('#flash_notice').avgrund({
			height: 200,
			openOnEvent: false,
			holderClass: 'custom',
			showClose: true,
			showCloseText: 'Close',
			enableStackAnimation: true,
			onBlurContainer: '#main',
			template: '<p>Sua hora extra foi computada, aperta esc.</p>'
		});
	});
</script>

<%= render "shared/menu" %>
<div class="span10 offset1">
	<h1>Registro de Horas Extras</h1>
	<p class="txt-descricao">Aqui são preenchidas as horas extras e sua justificativa. Seu nome de usuário será registrado quando você enviar este formulário.</p>
	<% if user_signed_in? %>

		<%= form_for @overtime, :html => { :class => 'form-horizontal' } do |f| %>

			  <% if @overtime.errors.any? %>
			    <div id="error_explanation" class="alert alert-error">
			      <h2><%=@overtime.errors.count %> <%= (@overtime.errors.count==1)? "erro encontrado":"erros encontrados" %></h2>
			      <ul>
				      <% @overtime.errors.full_messages.each do |msg| %>
				        <li><%= msg %></li>
				      <% end %>
				  </ul>
			    </div>
			  <% end %>
			
			<div class="span9">
				<div class="control-group">
					<%= f.label :Por_que_foi_necessário_o_trabalho_em_hora_extra?, :class => 'control-label' %>
					<div class="controls">
						<%= f.text_area :description, :class => 'text_field' %>
					</div>
				</div>
				<div class="control-group">
					<%= f.label :Início_da_hora_extra, :class => 'control-label' %>
					<div class="controls">
						<%= f.datetime_select :start_overtime, :class => '' %>					
					</div>
				</div>	
				<div class="control-group">
					<%= f.label :Fim_da_hora_extra, :class => 'control-label' %>
					<div class="controls">
						<%= f.datetime_select :end_overtime, :class => '' %>					
					</div>
				</div>	
			  	<div class="field">
				    <%= f.label :Projeto %>
				     <%= select(:overtime, :project_id, (Project.all.collect {|project| [ project.client.name+ " - " +project.name , project.id ] }).sort, { :prompt => 'Selecione um projeto' })      %>
				   
			  	</div>
			</div>
			<div class="form-actions btRegistrar span10">
				<%= f.submit :registrar, :class => 'btn btn-warning' %>				
			</div>
		<% end %>

	<% end %>
</div>







app/views/overtimes/no_approved.html.erb
asdsadasdsa

app/views/overtimes/rh.html.erb

<script src="bootstrap-datepicker.js">
   $('.datepicker').datepicker();
</script>
<h1>RH no comando</h1>

<%= render "shared/menu" %>
    <div class="input-append date datepicker" id="dp3" data-date="12-02-2012" data-date-format="dd-mm-yyyy">
    <input class="span2" size="16" type="text" value="12-02-2012">
    <span class="add-on"><i class="icon-th"></i></span>
    </div>   
    <div class="pull-left" > <%=select("user", "user_id", @users.collect{|user| [ user.name, user.id ] }, { :prompt => 'Selecione um usuario' }) %></div>
    <div class="pull-rightt" >
     <%= link_to "Gerar Excel", rh_path(format: "csv")  %>  
   </div>
   <div style="clear: both;"></div>
    <table data-filter="#filter" class="footable">
      <thead>
        <tr>
          <th data-class="expand" data-sort-initial="true">
            Usuario 
          </th>
          <th>
            Projeto
          </th>
          <th data-hide="phone,tablet">
            Horario Inicial
          </th>
          <th data-hide="phone,tablet" data-type="numeric"> 
            Horario Final
          </th>
          <th data-hide="phone">
            Motivo
          </th>
          
          <th data-hide="phone">
            Status
          </th>
        </tr>
      </thead>
      <tbody>
        <% @overtimes.each do |overtime| %>
          <tr>
            <td><%= overtime.project.name %></td>
            <td><%= overtime.user.name %></td>
            <td><%= overtime.start_overtime.strftime('%d/%m/%Y %H:%M') %></td>
            <td><%= overtime.end_overtime.strftime('%d/%m/%Y %H:%M') %></td>
            <td data-value="suspended"><%= overtime.description %></td>
            <td data-value="suspended">
              <% if overtime.status == "pedding" 
                  concat image_tag("suspended.png")           
               else overtime.status == "approved"
                  concat image_tag("active.png") 
              end
              %>              
          </tr>
      <% end %> 
      </tbody>
    </table>

    



     

app/views/overtimes/rh.xml.erb
<table border="1">
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Release Date</th>
    <th>Price</th>
  </tr>
   <% @overtimes.each do |overtime| %>
    <tr>
      <td><%= overtime.project.name %></td>
      <td><%= overtime.user.name %></td>
      <td><%= overtime.start_overtime.strftime('%d/%m/%Y %H:%M') %></td>
      <td><%= overtime.end_overtime.strftime('%d/%m/%Y %H:%M') %></td>
      <td data-value="suspended"><%= overtime.description %></td>
      <td data-value="suspended">
      <% if overtime.status == "pedding" 
         concat image_tag("suspended.png")           
         else overtime.status == "approved"
          concat image_tag("active.png") 
         end
         %>              
    </tr>
  <% end %>
</table

app/views/overtimes/show.html.erb
<%= render "shared/menu" %>


<p id="notice"><%= notice %></p>

<p>
  <b>Descrição:</b>
  <%= @overtime.description %>
</p>

<p>
  <b>Início da hora extra:</b>
  <%= @overtime.start_overtime.strftime('%d/%m/%Y %H:%M') %>
</p>

<p>
  <b>Fim da hora extra:</b>
  <%= @overtime.end_overtime.strftime('%d/%m/%Y %H:%M') %>
</p>

<p>
  <b>Projeto:</b>
  <%= @overtime.project.name %>
</p>

<%= link_to 'Confirmar Hora Extra', '/horas-extras' %>